name: "onnx-danodel"
platform: "onnxruntime_onnx"
max_batch_size: 0


input [
    {
        name: "INPUT"
        data_type: TYPE_FP32
        dims: [ 96 ]
    }
]

output [
    {
        name: "PROBABILITY"
        data_type: TYPE_FP32
        dims: [ 2 ]
    }
]

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]

dynamic_batching: { }
