train:
  train_size: 0.85
  dataset: train.csv
  target: round_winner
  batch_size: 1024
  epochs: 2
  lr: 3e-3
  random_state: 42

test:
  dataset: test.csv
  target: round_winner
  batch_size: 1024
